version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - migrate

  migrate:
    image: migrate/migrate
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "$DATABASE_URL",
        "up"
      ]
    volumes:
      - ./api/migrations:/migrations
    restart: "no"

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: always
